version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: face_gate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: face_gate_db
    ports:
      - 2000:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
