services:
  postgres:
    image: postgres
    container_name: face_gate
    ports:
      - 2400:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=face_gate_db
