name: Deploy Dockerhub

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t philip303/face_gate:latest .

      - name: Push Docker image to Docker Hub
        run: docker push philip303/face_gate:latest

      - name: Deploy Docker Container on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            echo "Pulling latest Docker image from Docker Hub..."
            sudo docker pull philip303/face_gate:latest
            
            if [ $(sudo docker ps -q -f name=face_gate_container) ]; then
              echo "Stopping existing container..."
              sudo docker stop face_gate_container
              sudo docker rm face_gate_container
            else
              echo "No existing container found, creating a new one..."
            fi
            
            echo "Running the new container..."
            sudo docker run -d -p 9100:9100 --name face_gate_container philip303/face_gate:latest
            echo "Container deployed successfully!"
            
            echo "Listing running containers..."
            sudo docker ps
